---
# An example of basic hosts-file configuration where first node hosts orderer
all:
  hosts: # localhost connection parameters, used for storing configuration while transferring it between nodes
    localhost:
      ansible_connection: local
  vars:
    domain: example.com
    # additional_channels: # optional, common channels are created by default. Just comment it out, if you don't need additional channels.
    #   - name: first-channel # channel name
    #     particapants: # Organizations, should be included in channel
    #     - org0
    #     - org1
    #   - name: second-channel
    #     particapants:
    #     - org0
    #     - org2
    #   - name: third-channel
    #     particapants:
    #     - org1
    #     - org2
    orderer_type: solo
  children:
    nodes:
      hosts:
        orderer.example.com: #Name of your first node
          node_roles: # Describes which containers will run on this node
            - root_orderer
            - orderer
            - peer
            - root_peer
            - explorer
          org: org0 # Organization name
          ansible_host: 1.2.3.4 # Real ip address
          ansible_user: ubuntu # User with sudo access
          ansible_private_key_file: ~/test.pem # Private key to identify ourselves
        # Same structure for any other nodes
        one.example.com:
          node_roles:
            - peer
          org: org1
          ansible_host: 1.2.3.5
          ansible_user: ubuntu
          ansible_private_key_file: ~/test.pem
        two.example.com:
          node_roles:
            - peer
          org: org2
          ansible_host: 1.2.3.6
          ansible_user: ubuntu
          ansible_private_key_file: ~/test.pem
